### PR TITLE
Merge messages posted while offline

### PR DESCRIPTION
**Pull request by mattwynne**

### CODE REVIEW

**Comment by blaine** [comment]
WIP noted so I'm not sure if/how much feedback you want, but overall looks great! Nice work getting anything done after your week & the party!!

The one tweak I'd suggest is that "sent" as a property of the message is very complicated. In the long term, read receipts are probably going to be more reliable/useful for this system, but I can also see the value of a "sent" status in a single node configuration while we're getting started (and it's definitely arguable that our "server sync" ought to be reliable enough that "sent to one node" _effectively_ means "sent to all local nodes."

Just thinking out loud, but I wonder if we had different "names" for different nodes, then we could show an indication of which nodes have the message? Sort of a sent-as-set, rather than boolean? Might be useful for debugging the lora stuff too?

**Comment by mattwynne** [comment]
Feedback always welcome, that's why it's in a PR not just a branch 😄 

I think there are a few things we could know about the "deliveredness" of the message, on the client:

- which server node(s?) we have sent it to
- which server node(s?) have "acknowledged" it in their `message-list`
- which users have seen the message

I do like the idea of the nodes having identifying names, that's nice. Would we get the name in some kind of initial handshake maybe? Then as you say the client could store the name of the node it has sent it to instead of a boolean. But if the message got broadcast node-to-node would we then go and update the clients?

I ignored the idea of message acknowledgment for now as it seemed a bit overkill, but we could try it. It would definitely be more thorough than assuming that a `200` response means the server was actually able to store the message.

I don't clearly see how read receipts could work in a multi-user chat...? seems to me like that would need more endpoints/data stores on the server to store the read receipts? Because if we mutate the message to unclude who has read it, the content address will change, right? So it would need to be a separate hash/file on the server?

**Comment by blaine** [comment]
I suspect there's a more elegant solution, but we could use bloom filters for received receipts; false positives are a possibility, but we could use large enough ones that it's infinitesimally small. Each server *and* user could provide a bloom filter of messages, and that way when we have a concept of contacts/friends, it'd be possible to see if the message has been received by so-and-so or node-and-such.

I'm imagining having special icons for nodes, so you can see e.g. that your message is at the top of 🐦‍⬛or 🗻 or 🌸 or at the :lodge: or :hummingbird: etc

**Comment by blaine** [comment]
(should add that this plays nicely with immutable messages, since we don't change the message, just add a new mutable k-v store (can still be filesystem) with the keys as "user IDs" and the values as the bloom filter, plus a monotonic version and maybe a signature?)

**Comment by mattwynne** [comment]
OK, so each "reader" (a user or a node) would have a bloom filter value in the k-v store (on the server), and we'd update that value whenever the read status of a message changed? What does the signature do?

**Comment by mattwynne** [comment]
Or what about the other way around, and store a filter per message, and then the filter just says who has read it. Less chance of collisions that way around?

**Comment by mattwynne** [comment]
https://www.npmjs.com/package/bloom-filters seems legit

**Comment by mattwynne** [comment]
My reflection on this, after discussions in real life last night, is that we should merge this, and then iterate towards read receipts once we've got a working server implementation in rust.

**Comment by blaine** [comment]
GitHub *refuses* to give me push notifications (even with the app installed!) so just seeing this, but who doesn't like a merge on Christmas morning? 🎅

**Comment by mattwynne** [comment]
🎄

**Pull request merged**
